### ISSUE TITLE
extension doesn't work when providing a reference Word doc for styling

### ISSUE THREAD

**Issue by jr-leary7** [kapsner/authors-block#10]
Hi, love the extension ! It's been super useful. Today when attempting to use it I found that the Word output of `authors-block`, notably the institution & corresponding author labels, don't appear [when a reference Word doc is provided to Quarto](https://quarto.org/docs/output-formats/ms-word-templates.html) like so:

```
format:
  docx: 
    reference-doc: reference_doc.docx 
```
Are there any known workarounds for this?

**Comment by kapsner** [comment]
Hi, I cannot reproduce the issue - I am using reference docs as well and had no issues so far. Could you please provide more information? The full related yaml header would be great!
Also, do you start your reference doc from a quarto-rendered document?

**Comment by kapsner** [comment]
I've also noticed that I add the filter below the format:

```yaml
format:
  docx:
    filters:
      - kapsner/authors-block
    reference-doc: template.docx
```

Could you pls try if this solves your issue?

**Comment by jr-leary7** [comment]
I updated my Quarto version (I'm using the nightly build) & the issue disappeared. Thanks for the quick reply !
