### ISSUE TITLE
Two authors should not have a comma between them

### ISSUE THREAD

**Issue by Benjamin-Lee** [kapsner/authors-block#12]
This is only needed for more than two authors and appears to be a bug. Example:

<img width="382" alt="image" src="https://github.com/user-attachments/assets/02a7d9b4-63cd-48f6-aa87-e9ed12b9c3e3">

**Comment by kapsner** [comment]
Hi @Benjamin-Lee , thanks for reporting this. That's correct, in case of two authors, there should be no comma. This is probably related to [this code](https://github.com/kapsner/authors-block/blob/82c8663b5646f9a2c5b91e279a81b9ea235ca907/_extensions/authors-block/from_author_info_blocks.lua#L173), where all cases with >1 authors are handled the same. 
I will have a look into it.

**Comment by kapsner** [comment]
@Benjamin-Lee pls check, if this solves your issue. Install the development version to try out `quarto add kapsner/authors-block@development`

**Comment by Benjamin-Lee** [comment]
That worked! Thanks so much for the help.

**Comment by kapsner** [comment]
Great, you are welcome
