### ISSUE TITLE
Add categories/topics

### ISSUE THREAD

**Issue by mcanouil** [kapsner/authors-block#4]
Hi @kapsner,
May I suggest you to add topics/categories in your GitHub repository corresponding field?
Currently, your repository is not really discoverable by search engine, especially GitHub one.

See for examples <https://github.com/mcanouil/quarto-animate>.

PS: I am using GitHub API to search for new Quarto content to add to the Awesome Quarto list, but your extension did not show up. Your extension was mentioned in a Quarto GitHub Discussion and then suggested to me, see <https://github.com/mcanouil/awesome-quarto/issues/255>.

**Comment by kapsner** [comment]
Thanks for that hint - I've just added some tags to the repo. And btw - very nice list of awesome quarto extensions!
